services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: projectmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: backend_app
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/projectmanagement?schema=public
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
